public interface Constants {
    double BONUS = 1.25;
    double DEBUFF = 0.75;
    double ATTACK_BONUS = 1.2;
    double ATTACK_BOOSTER = 1.2;
    double K_O = 0.0;
    int STARTING_CREDITS = 10;
    int MAX_INVENTORY_SIZE = 5;
    int NUM_ITEMS_IN_GAME = 3;
    int ITEM_COST = 4;
    int MAX_HP = 100;
    int HEAL_HP = 34;
    int ACTION_BUY = 0;
    int ACTION_BATTLE = 1;
    int MIN_HP_ATTACK = 30;
    int BATTLE_REWARD = 2;
    double WILD_MON_HEALTH_DEBUFF = .4;
    int ATTACK_ID_CONSTRUCT = 1;
    int HEALING_POTION_THRESHOLD = 40;
    double LEVEL_BONUS = 1.2;
    int MAX_LEVEL = 4;
}
